# Generated by Django 4.2.7 on 2023-11-09 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarPass",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("brand", models.CharField(max_length=48)),
                ("model", models.CharField(max_length=48)),
                ("plate_number", models.CharField(max_length=24)),
                ("owners_name", models.CharField(max_length=96)),
                ("created_ad", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
